// Package checkout is the synthetic reference system: a three-stage
// payment lifecycle (auth, capture, settle) with seeded traffic on an
// hour-of-week curve and an in-memory ledger that serves as ground truth
// for the engine.
//
// Modeling honesty: there are no service or queue objects here. The
// capture and settle stages are FIXED per-transaction pipeline delays
// standing in for queue latency — load-independent by design in this
// baseline. Contention, stalls, and failures arrive with the
// fault-injection knobs (the next build step); do not design engine
// expectations against queueing behavior this baseline does not have.
//
// The simulation is discrete-event on a virtual clock (minute resolution,
// single-threaded): determinism under a seed is structural, not a property
// tests hope for. Scope of that claim: byte-identical ledgers are
// guaranteed for the same toolchain and architecture. Arrival sampling
// consumes math.Exp, which Go does not promise bit-identical across
// platforms — so GOLDEN expected values must be generated by CI
// (ubuntu/amd64), never on a laptop. All fixtures produced here are
// synthetic by construction — never derived from real data.
package checkout

import (
	"fmt"
	"math"
	"math/rand/v2"
	"time"
)

// State is a transaction's lifecycle state in the ledger.
type State string

const (
	StateCreated  State = "created"        // arrived, auth not yet attempted
	StateAuthed   State = "authed"         // auth ok, inside the capture pipeline delay
	StateCaptured State = "captured"       // capture ok, inside the settle pipeline delay
	StateSettled  State = "settled"        // terminal success
	StateAuthFail State = "failed_auth"    // terminal: rejected at the api
	StateCapFail  State = "failed_capture" // terminal: capture-worker rejected
)

// Segment mirrors the two customer segments the proposal's registry
// enumerates.
type Segment string

const (
	SegmentSMB        Segment = "smb"
	SegmentEnterprise Segment = "enterprise"
)

// Txn is one synthetic invoice payment — a ledger row. Amounts are int64
// minor units; time fields are zero until the stage happens.
type Txn struct {
	ID          string
	CustomerID  string // pre-hashed form, e.g. "h:c000042"
	Segment     Segment
	AmountMinor int64
	Currency    string

	CreatedAt  time.Time
	AuthedAt   time.Time
	CapturedAt time.Time
	SettledAt  time.Time

	State State
}

// Ledger is the ground truth: every synthetic transaction ever created,
// in creation order.
type Ledger struct {
	Txns []Txn
}

// Explicit-zero sentinels. The zero value of each tuning knob means "use
// the default", so a scenario that wants a LITERAL zero spells it with
// these. Any other negative value is a configuration error and Run panics.
const (
	NoEnterprise = -1.0 // EnterpriseFraction: all-SMB traffic
	InstantStage = -1   // CaptureDelayMin / SettleDelayMin: zero delay
)

// Config drives one simulation run. The zero values of the tuning knobs
// are replaced by defaults in Run (see the sentinels above for literal
// zeros).
type Config struct {
	Seed  uint64
	Start time.Time // aligned down to the minute
	End   time.Time

	// Curve is the hour-of-week arrival-rate curve (mean arrivals per
	// minute for each of the 168 hours, Monday 00:00 = index 0). Nil means
	// DefaultCurve.
	Curve *[168]float64

	// EnterpriseFraction is the probability a customer is enterprise
	// (default 0.1).
	EnterpriseFraction float64

	// Customers is the size of the synthetic customer pool (default 3000).
	Customers int

	// Service times (defaults: capture 2 min, settle 5 min). Every
	// transaction spends this long in the queue stage before its worker
	// completes it — a simple, fully deterministic pipeline delay.
	CaptureDelayMin int
	SettleDelayMin  int
}

// Result of a run: the ground-truth ledger plus the effective config.
type Result struct {
	Ledger Ledger
	Config Config
}

// maxRatePerMinute bounds curve rates: far above any realistic synthetic
// load, far below where the Knuth sampler's exp(-lambda) underflows
// (which would silently cap arrival counts instead of failing).
const maxRatePerMinute = 60.0

func (c *Config) applyDefaults() {
	if c.Curve == nil {
		curve := DefaultCurve()
		c.Curve = &curve
	}
	for i, r := range c.Curve {
		if r < 0 || r > maxRatePerMinute {
			panic(fmt.Sprintf("checkout: curve[%d] = %v outside [0, %v] — scenario config error", i, r, maxRatePerMinute))
		}
	}
	switch {
	case c.EnterpriseFraction == 0:
		c.EnterpriseFraction = 0.1
	case c.EnterpriseFraction == NoEnterprise:
		c.EnterpriseFraction = 0
	case c.EnterpriseFraction < 0 || c.EnterpriseFraction > 1:
		panic(fmt.Sprintf("checkout: EnterpriseFraction %v invalid — scenario config error", c.EnterpriseFraction))
	}
	if c.Customers == 0 {
		c.Customers = 3000
	}
	c.CaptureDelayMin = delayKnob("CaptureDelayMin", c.CaptureDelayMin, 2)
	c.SettleDelayMin = delayKnob("SettleDelayMin", c.SettleDelayMin, 5)
}

func delayKnob(name string, v, def int) int {
	switch {
	case v == 0:
		return def
	case v == InstantStage:
		return 0
	case v < 0:
		panic(fmt.Sprintf("checkout: %s = %d invalid (use InstantStage for a literal zero) — scenario config error", name, v))
	}
	return v
}

// Run executes the simulation and returns the ground-truth ledger.
// Identical Config (including Seed) yields a byte-identical ledger on the
// same toolchain and architecture — see the package doc for why golden
// values must come from CI. Run panics on invalid tuning knobs: a broken
// scenario must never produce plausible-looking ground truth.
func Run(cfg Config) Result {
	cfg.applyDefaults()
	rng := rand.New(rand.NewPCG(cfg.Seed, cfg.Seed^0x9e3779b97f4a7c15))

	start := cfg.Start.Truncate(time.Minute)
	end := cfg.End.Truncate(time.Minute)

	var ledger Ledger
	n := 0
	for t := start; t.Before(end); t = t.Add(time.Minute) {
		rate := cfg.Curve[hourOfWeek(t)]
		arrivals := poisson(rng, rate)
		for i := 0; i < arrivals; i++ {
			n++
			txn := newTxn(rng, cfg, n, t)

			// auth at the api: instantaneous in the fault-free baseline.
			txn.AuthedAt = t
			txn.State = StateAuthed

			// capture-worker completes after the pipeline delay, then
			// settle-worker after its own — unless the window ends first,
			// in which case the transaction is left in flight at the
			// state it truthfully reached.
			capAt := t.Add(time.Duration(cfg.CaptureDelayMin) * time.Minute)
			if capAt.Before(end) {
				txn.CapturedAt = capAt
				txn.State = StateCaptured
				setAt := capAt.Add(time.Duration(cfg.SettleDelayMin) * time.Minute)
				if setAt.Before(end) {
					txn.SettledAt = setAt
					txn.State = StateSettled
				}
			}
			ledger.Txns = append(ledger.Txns, txn)
		}
	}
	return Result{Ledger: ledger, Config: cfg}
}

func newTxn(rng *rand.Rand, cfg Config, n int, t time.Time) Txn {
	seg := SegmentSMB
	// Amounts in minor units, integer arithmetic only: SMB around $142,
	// enterprise around $910, both with wide spreads.
	amount := int64(4200) + rng.Int64N(20000)
	if rng.Float64() < cfg.EnterpriseFraction {
		seg = SegmentEnterprise
		amount = int64(31000) + rng.Int64N(120000)
	}
	return Txn{
		ID:          fmt.Sprintf("inv_%08d", n),
		CustomerID:  fmt.Sprintf("h:c%06d", rng.IntN(cfg.Customers)),
		Segment:     seg,
		AmountMinor: amount,
		Currency:    "USD",
		CreatedAt:   t,
		State:       StateCreated,
	}
}

// hourOfWeek maps a time to 0..167 with Monday 00:00 as index 0, in UTC.
func hourOfWeek(t time.Time) int {
	t = t.UTC()
	day := (int(t.Weekday()) + 6) % 7 // Monday = 0
	return day*24 + t.Hour()
}

// poisson draws a Poisson-distributed arrival count via Knuth's method —
// exact for the small per-minute rates the curve produces, and fully
// deterministic under the run's rng.
func poisson(rng *rand.Rand, lambda float64) int {
	if lambda <= 0 {
		return 0
	}
	l := math.Exp(-lambda)
	k := 0
	p := 1.0
	for {
		p *= rng.Float64()
		if p <= l {
			return k
		}
		k++
	}
}
