// Copyright 2026 Yauvan Suba
// SPDX-License-Identifier: Apache-2.0

// Command wikisync regenerates the GitHub wiki page set from docs/ and
// README.md. The wiki is a derived mirror: docs/ in the repository is the
// source of truth (ADR-0008), and the sync workflow (workspace-ehd)
// overwrites wiki-side edits with this tool's output.
//
// Usage: go run ./test/wikisync -repo <repo-root> -out <dir>
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const repoURL = "https://github.com/NightWatchEng/shortfall"

// pageName maps a repo-relative markdown path to its flat wiki page name:
// the docs/ prefix and .md suffix drop, remaining path separators become
// hyphens. README.md at the repo root maps to README.
func pageName(p string) string {
	p = strings.TrimSuffix(p, ".md")
	p = strings.TrimPrefix(p, "docs/")
	return strings.ReplaceAll(p, "/", "-")
}

// notMirrored names directories under docs/ the wiki does not publish.
// docs/internal holds founder- and maintainer-facing records (the go-public
// checklist) that have no reader on a public docs site; mirroring them would
// put project bookkeeping in the same nav as the guides.
var notMirrored = map[string]bool{"docs/internal": true}

// docPages returns repo-relative source path -> wiki page name for every
// mirrored markdown file: README.md plus each .md under docs/, except the
// directories notMirrored names.
func docPages(root string) (map[string]string, error) {
	pages := map[string]string{}
	owner := map[string]string{} // page name -> source path that claimed it
	claim := func(src string) error {
		page := pageName(src)
		if prev, taken := owner[page]; taken {
			return fmt.Errorf("wiki page %q generated by both %s and %s; rename one source", page, prev, src)
		}

		owner[page] = src
		pages[src] = page
		return nil
	}
	if _, err := os.Stat(filepath.Join(root, "README.md")); err == nil {
		if err := claim("README.md"); err != nil {
			return nil, err
		}
	}

	err := filepath.WalkDir(filepath.Join(root, "docs"), func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}

		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if notMirrored[rel] {
				return filepath.SkipDir
			}

			return nil
		}

		if !strings.HasSuffix(p, ".md") {
			return nil
		}

		return claim(rel)
	})
	if err != nil {
		return nil, err
	}

	return pages, nil
}

// linkRE matches inline markdown link destinations. Reference-style links
// do not occur in docs/; the sync test set pins the shapes that do.
var linkRE = regexp.MustCompile(`\]\(([^)\s]+)\)`)

// rewriteLine rewrites every relative link destination on one line of the
// source file src (repo-relative), leaving inline code spans (single
// backticks) verbatim. Mirrored .md targets become wiki page names (anchors
// preserved); other repo paths become GitHub blob/tree URLs; absolute URLs
// and pure-anchor links pass through.
func rewriteLine(root, src string, pages map[string]string, line string) string {
	segs := strings.Split(line, "`")
	for i := 0; i < len(segs); i += 2 { // even segments sit outside spans
		segs[i] = rewriteSegment(root, src, pages, segs[i])
	}

	return strings.Join(segs, "`")
}

func rewriteSegment(root, src string, pages map[string]string, seg string) string {
	return linkRE.ReplaceAllStringFunc(seg, func(m string) string {
		dest := m[2 : len(m)-1]
		if strings.Contains(dest, "://") || strings.HasPrefix(dest, "#") || strings.HasPrefix(dest, "mailto:") {
			return m
		}

		target, anchor := dest, ""
		if i := strings.IndexByte(dest, '#'); i >= 0 {
			target, anchor = dest[:i], dest[i:]
		}

		resolved := path.Clean(path.Join(path.Dir(src), target))
		if page, ok := pages[resolved]; ok {
			return "](" + page + anchor + ")"
		}

		info, err := os.Stat(filepath.Join(root, filepath.FromSlash(resolved)))
		if err != nil {
			// Target does not exist in the tree; leave the link as
			// written rather than inventing a destination.
			return m
		}

		kind := "blob"
		if info.IsDir() {
			kind = "tree"
		}

		return "](" + repoURL + "/" + kind + "/main/" + resolved + anchor + ")"
	})
}

// rewriteDoc applies rewriteLine outside fenced code blocks and leaves
// fenced content byte-identical.
func rewriteDoc(root, src string, pages map[string]string, body string) string {
	lines := strings.Split(body, "\n")
	inFence := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}

		if !inFence {
			lines[i] = rewriteLine(root, src, pages, line)
		}
	}

	return strings.Join(lines, "\n")
}

// navEntry is one curated line of the Home/_Sidebar navigation: the wiki
// page name and the title it is listed under.
type navEntry struct{ page, title string }

// section groups curated pages for navigation in a fixed reading order —
// start here, then reference, then the design record. Order is the whole
// point: a reader arriving at the wiki should be able to follow it top to
// bottom, so this list is maintained by hand rather than sorted.
type section struct {
	title   string
	entries []navEntry
}

var sections = []section{
	{"Start here", []navEntry{
		{"README", "Introduction"},
		{"quickstart", "Quickstart"},
		{"integration", "Integration guide"},
		{"example-webhooks", "Worked example: webhook Lambdas"},
	}},
	{"Reference", []navEntry{
		{"adapters", "Backends & adapters"},
		{"registry", "Registry"},
		{"money", "Money & the legs"},
		{"performance", "Performance"},
	}},
	{"Specification", []navEntry{
		{"portability", "Portability contract"},
	}},
	{"Architecture", []navEntry{
		{"architecture-README", "Overview"},
		{"architecture-c4-l1-context", "C4 L1 — system context"},
		{"architecture-c4-l2-containers", "C4 L2 — containers"},
		{"architecture-c4-l3-components", "C4 L3 — components"},
		{"architecture-money-path", "The money path"},
	}},
	{"Design decisions", []navEntry{
		{"adr-README", "All decision records"},
	}},
}

// indexed names a page set that one index page lists, rather than the
// navigation listing each member — eighteen ADRs or eight spec chapters
// would bury the guides. Reachability is checked against the index, not
// assumed: see indexLinks. The index page itself takes the ordinary
// curated route, so nothing is exempt.
type indexed struct {
	prefix string // wiki page-name prefix its members carry
	src    string // repo-relative index that must link them
}

var indexes = []indexed{
	{"adr-", "docs/adr/README.md"},
	{"portability-", "docs/portability.md"},
}

// indexFor returns the index owning page, if any. The index page itself
// carries no prefix of its own — docs/portability.md is "portability",
// not "portability-…" — so it never matches and stays curated.
func indexFor(page string) (indexed, bool) {
	for _, ix := range indexes {
		if strings.HasPrefix(page, ix.prefix) {
			return ix, true
		}
	}

	return indexed{}, false
}

// navFor renders the curated navigation, and fails on a page nothing would
// link to. A new doc under docs/ is mirrored automatically, so without this
// the wiki grows pages reachable only by URL (CONTRIBUTING, "Documentation
// accuracy"). A page is reachable two ways: a nav section names it, or it
// is an ADR the ADR index links — and the index itself takes the first
// route, so nothing is exempt.
func navFor(root string, pages map[string]string) (string, error) {
	linked := map[string]map[string]bool{}
	for _, ix := range indexes {
		l, err := indexLinks(root, ix.src)
		if err != nil {
			return "", err
		}

		linked[ix.src] = l
	}

	uncovered := make(map[string]string, len(pages)) // page -> why it is unreachable
	for src, page := range pages {
		if ix, ok := indexFor(page); ok && src != ix.src {
			if !linked[ix.src][path.Base(src)] {
				uncovered[page] = "link it from " + ix.src
			}

			continue
		}

		uncovered[page] = "add an entry to sections in test/wikisync/main.go"
	}

	var b strings.Builder
	for _, s := range sections {
		var lines []string
		for _, e := range s.entries {
			if !containsPage(pages, e.page) {
				continue // curated but not present in this tree
			}

			delete(uncovered, e.page)
			lines = append(lines, "- ["+e.title+"]("+e.page+")\n")
		}

		if len(lines) == 0 {
			continue
		}

		b.WriteString("\n### " + s.title + "\n\n")
		for _, l := range lines {
			b.WriteString(l)
		}
	}

	if len(uncovered) > 0 {
		reasons := make([]string, 0, len(uncovered))
		for page, how := range uncovered {
			reasons = append(reasons, page+" ("+how+")")
		}

		sort.Strings(reasons)
		return "", fmt.Errorf("wiki page(s) nothing would link to: %s", strings.Join(reasons, "; "))
	}

	return b.String(), nil
}

// indexLinks returns the set of filenames an index page links, so a member
// left out of it is caught here rather than published as an orphan. A
// missing index yields an empty set and so fails every page behind it,
// which is the fail-closed direction: an index that vanished orphans its
// whole set at once, and that must be loud.
func indexLinks(root, src string) (map[string]bool, error) {
	body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(src)))
	if errors.Is(err, os.ErrNotExist) {
		return map[string]bool{}, nil
	}

	if err != nil {
		return nil, err
	}

	linked := map[string]bool{}
	for _, dest := range linkTargets(string(body)) {
		linked[path.Base(strings.SplitN(dest, "#", 2)[0])] = true
	}

	return linked, nil
}

// linkTargets returns every inline link destination markdown would actually
// render, skipping fenced blocks and inline code spans exactly as
// rewriteDoc does. An ADR named only inside a fenced example is not linked
// by it, and must not count as reachable.
func linkTargets(body string) []string {
	var dests []string
	inFence := false
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}

		if inFence {
			continue
		}

		segs := strings.Split(line, "`")
		for i := 0; i < len(segs); i += 2 { // even segments sit outside spans
			for _, m := range linkRE.FindAllStringSubmatch(segs[i], -1) {
				dests = append(dests, m[1])
			}
		}
	}

	return dests
}

// containsPage reports whether any source maps to the given wiki page.
func containsPage(pages map[string]string, page string) bool {
	for _, p := range pages {
		if p == page {
			return true
		}
	}

	return false
}

const homePreamble = `# shortfall

**What an incident cost, who it hit, and how sure you are.**

shortfall is a Go library and CLI that measures the dollar impact of an
incident from telemetry your services already emit, and reports it in a
form Finance can audit. New here? Read the
[introduction](README), then the [quickstart](quickstart).

This wiki is a generated mirror of the repository's ` + "[`docs/`](" + repoURL + "/tree/main/docs)" + ` directory,
which is the source of truth: documentation changes in the same PR as the
behavior it describes (ADR-0008). Edits made directly to wiki pages are
overwritten by the next sync run.
`

func generate(root, out string) error {
	pages, err := docPages(root)
	if err != nil {
		return err
	}

	srcs := make([]string, 0, len(pages))
	for src := range pages {
		srcs = append(srcs, src)
	}

	sort.Strings(srcs)
	for _, src := range srcs {
		body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(src)))
		if err != nil {
			return err
		}

		rewritten := rewriteDoc(root, src, pages, string(body))
		footer := fmt.Sprintf(
			"\n\n---\n_Generated mirror of [`%s`](%s/blob/main/%s). The repository is the source of truth; wiki edits are overwritten by the sync workflow._\n",
			src, repoURL, src)
		dest := filepath.Join(out, pages[src]+".md")
		if err := os.WriteFile(dest, []byte(rewritten+footer), 0o644); err != nil {
			return err
		}
	}

	nav, err := navFor(root, pages)
	if err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(out, "Home.md"), []byte(homePreamble+nav), 0o644); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(out, "_Sidebar.md"), []byte(nav), 0o644)
}

func main() {
	root := flag.String("repo", ".", "repository root")
	out := flag.String("out", "", "output directory for the generated page set")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "wikisync: -out is required")
		os.Exit(2)
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "wikisync:", err)
		os.Exit(1)
	}

	if err := generate(*root, *out); err != nil {
		fmt.Fprintln(os.Stderr, "wikisync:", err)
		os.Exit(1)
	}
}
