// Copyright 2026 Yauvan Suba
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"strings"
	"testing"
)

// TestEveryTrackedGoFileCarriesTheHeader is the durable guard: a new
// .go file without the two-line Apache-2.0 header fails the ordinary
// test step, naming the file and the fix command.
func TestEveryTrackedGoFileCarriesTheHeader(t *testing.T) {
	missing, err := run("../..", false)
	if err != nil {
		t.Fatalf("scanning tracked files: %v", err)
	}

	if len(missing) > 0 {
		t.Errorf("%d file(s) missing the Apache-2.0 header (run: go run ./test/licensehdr -fix):\n%s",
			len(missing), strings.Join(missing, "\n"))
	}
}

// The cases below pin the check itself, so the guard cannot pass
// vacuously: a headerless file must be flagged and fixed to the exact
// header, a generated file must be exempt, and the fixed forms of the
// tricky layouts (build tag, package doc comment) must be what the
// decision record specifies.
func TestNeedsHeader(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"headerless", "package a\n", true},
		{"exact header", header + "\npackage a\n", false},
		{"year range accepted", "// Copyright 2026-2027 Yauvan Suba\n// SPDX-License-Identifier: Apache-2.0\n\npackage a\n", false},
		{"wrong author", "// Copyright 2026 Someone Else\n// SPDX-License-Identifier: Apache-2.0\n\npackage a\n", true},
		{"spdx alone", "// SPDX-License-Identifier: Apache-2.0\n\npackage a\n", true},
		{"header not at top", "//go:build slow\n\n" + header + "\npackage a\n", true},
		{"generated file exempt", "// Code generated by stringer; DO NOT EDIT.\n\npackage a\n", false},
	}
	for _, tc := range cases {
		if got := needsHeader([]byte(tc.content)); got != tc.want {
			t.Errorf("%s: needsHeader = %v, want %v", tc.name, got, tc.want)
		}
	}
}

func TestWithHeader(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    string
	}{
		{
			"plain file",
			"package a\n",
			header + "\npackage a\n",
		},
		{
			"package doc comment stays attached",
			"// Package a does a thing.\npackage a\n",
			header + "\n// Package a does a thing.\npackage a\n",
		},
		{
			"build constraint stays legal",
			"//go:build slow\n\npackage a\n",
			header + "\n//go:build slow\n\npackage a\n",
		},
	}
	for _, tc := range cases {
		got := string(withHeader([]byte(tc.content)))
		if got != tc.want {
			t.Errorf("%s:\ngot:\n%s\nwant:\n%s", tc.name, got, tc.want)
		}

		if needsHeader([]byte(got)) {
			t.Errorf("%s: fixed content still reported missing", tc.name)
		}
	}
}
